# Generated by Django 5.2 on 2025-04-08 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Quadro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(blank=True, max_length=100, null=True)),
                ("nome", models.CharField(max_length=100)),
                ("responsavel", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("PROJETO NA FILA", "PROJETO NA FILA"),
                            ("EM NEGOCIAÇÃO", "EM NEGOCIAÇÃO"),
                            ("EXECUÇÃO DO TIME", "EXECUÇÃO DO TIME"),
                            ("APRESENTAÇÃO AO CLIENTE", "APRESENTAÇÃO AO CLIENTE"),
                            ("VALORES", "VALORES"),
                            ("ENTREGA AO CLIENTE", "ENTREGA AO CLIENTE"),
                        ],
                        default="PROJETO NA FILA",
                        max_length=50,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "quadro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="core.quadro",
                    ),
                ),
            ],
        ),
    ]
