# Generated by Django 5.2 on 2025-04-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadro",
            name="etapa",
            field=models.CharField(
                choices=[
                    ("PROJETO NA FILA", "PROJETO NA FILA"),
                    ("EM NEGOCIAÇÃO", "EM NEGOCIAÇÃO"),
                    ("EXECUÇÃO DO TIME", "EXECUÇÃO DO TIME"),
                    ("APRESENTAÇÃO AO CLIENTE", "APRESENTAÇÃO AO CLIENTE"),
                    ("VALORES", "VALORES"),
                    ("ENTREGA AO CLIENTE", "ENTREGA AO CLIENTE"),
                ],
                default="PROJETO NA FILA",
                max_length=50,
            ),
        ),
    ]
