# Generated by Django 5.2 on 2025-04-06 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_quadro_etapa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quadro",
            name="etapa",
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("PROJETO NA FILA", "Projeto na fila"),
                            ("EM NEGOCIAÇÃO", "Em negociação"),
                            ("EXECUÇÃO DO TIME", "Execução do time"),
                            ("APRESENTAÇÃO AO CLIENTE", "Apresentação ao cliente"),
                            ("VALORES", "Valores"),
                            ("ENTREGA AO CLIENTE", "Entrega ao cliente"),
                        ],
                        default="PROJETO NA FILA",
                        max_length=50,
                    ),
                ),
                (
                    "quadro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="core.quadro",
                    ),
                ),
            ],
        ),
    ]
