# Generated by Django 5.2 on 2025-04-06 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_quadro_etapa_tarefa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tarefa",
            name="situacao",
        ),
        migrations.AddField(
            model_name="quadro",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("PROJETO NA FILA", "PROJETO NA FILA"),
                    ("EM NEGOCIAÇÃO", "EM NEGOCIAÇÃO"),
                    ("EXECUÇÃO DO TIME", "EXECUÇÃO DO TIME"),
                    ("APRESENTAÇÃO AO CLIENTE", "APRESENTAÇÃO AO CLIENTE"),
                    ("VALORES", "VALORES"),
                    ("ENTREGA AO CLIENTE", "ENTREGA AO CLIENTE"),
                ],
                default="PROJETO NA FILA",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
