# Generated by Django 5.2 on 2025-04-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_tarefa_situacao_quadro_situacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadro",
            name="empresa",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
