# Generated by Django 5.2 on 2025-04-07 00:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_quadro_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="quadro",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
